// --- VARIABLES ---
let allResults = [];
let filteredResults = [];

// Elements
const tableBody = document.getElementById('resultsTableBody');
const loadingEl = document.getElementById('loading');
const searchInput = document.getElementById('searchInput');
const exportBtn = document.getElementById('exportBtn');

// --- LOAD DATA ---
async function loadData() {
    try {
        // Fetch the CSV file generated by our Python script
        const response = await fetch('sanctions_results.csv');
        const csvText = await response.text();
        
        Papa.parse(csvText, {
            header: true,
            skipEmptyLines: true,
            complete: function(results) {
                // We add a default "ReviewStatus" of "Pending" to each item
                allResults = results.data.map(item => ({
                    ...item,
                    ReviewStatus: 'Pending'
                }));
                filteredResults = [...allResults];
                renderTable();
                loadingEl.style.display = 'none';
            }
        });
    } catch (error) {
        console.error('Error loading CSV:', error);
        loadingEl.innerHTML = '<p style="color: red;">Error: Could not find "sanctions_results.csv". Make sure you have run the scraper script first!</p>';
    }
}

// --- RENDER TABLE ---
function renderTable() {
    tableBody.innerHTML = '';
    
    filteredResults.forEach((item, index) => {
        const row = document.createElement('tr');
        row.className = item.ReviewStatus.toLowerCase();
        
        // Status Column
        const statusCell = document.createElement('td');
        statusCell.textContent = item.ReviewStatus;
        statusCell.className = `status-${item.ReviewStatus.toLowerCase()}`;
        row.appendChild(statusCell);

        // Data Columns
        ['Name', 'Score', 'Schema', 'Topics', 'ID'].forEach(key => {
            const cell = document.createElement('td');
            cell.textContent = item[key] || '-';
            row.appendChild(cell);
        });

        // Actions Column
        const actionCell = document.createElement('td');
        
        const approveBtn = document.createElement('button');
        approveBtn.textContent = 'Approve';
        approveBtn.className = 'btn-approve';
        approveBtn.onclick = () => updateStatus(index, 'Approved');
        
        const rejectBtn = document.createElement('button');
        rejectBtn.textContent = 'Reject';
        rejectBtn.className = 'btn-reject';
        rejectBtn.onclick = () => updateStatus(index, 'Rejected');

        actionCell.appendChild(approveBtn);
        actionCell.appendChild(rejectBtn);
        row.appendChild(actionCell);

        tableBody.appendChild(row);
    });
}

// --- UPDATE STATUS ---
function updateStatus(filteredIndex, newStatus) {
    // Find the original item in allResults to update it
    const item = filteredResults[filteredIndex];
    const originalIndex = allResults.findIndex(res => res.ID === item.ID);
    
    if (originalIndex !== -1) {
        allResults[originalIndex].ReviewStatus = newStatus;
        renderTable(); // Re-draw the table to show the new status
    }
}

// --- SEARCH ---
searchInput.addEventListener('input', (e) => {
    const term = e.target.value.toLowerCase();
    filteredResults = allResults.filter(item => 
        item.Name.toLowerCase().includes(term) || 
        item.Topics.toLowerCase().includes(term) ||
        item.ID.toLowerCase().includes(term)
    );
    renderTable();
});

// --- EXPORT ---
exportBtn.addEventListener('click', () => {
    const csv = Papa.unparse(allResults);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'reviewed_sanctions.csv');
    link.click();
});

// Start!
loadData();
